// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfptsbRJeWvFrhZWBmJAkKL-W76ksButc',
    appId: '1:527419070527:web:baf52eeeb00e2df041c08a',
    messagingSenderId: '527419070527',
    projectId: 'atozpoint-41217',
    authDomain: 'atozpoint-41217.firebaseapp.com',
    storageBucket: 'atozpoint-41217.appspot.com',
    measurementId: 'G-7MNS1BSK4Y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfptsbRJeWvFrhZWBmJAkKL-W76ksButc',
    appId: '1:527419070527:web:ceae2738efce211a41c08a',
    messagingSenderId: '527419070527',
    projectId: 'atozpoint-41217',
    authDomain: 'atozpoint-41217.firebaseapp.com',
    storageBucket: 'atozpoint-41217.appspot.com',
    measurementId: 'G-FCYS2G7KGT',
  );
}
